### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN when using firefox 84.0.1 (64 bit) to navigate directly to xp.metagame.wtf

### ISSUE THREAD

**Issue by plasmacorral** [MetaFam/XP#26]
I did recently clear all my browser data out, so maybe I previously gave the exception and just moved on.  Today I get this SSL_ERROR_BAD_CERT_DOMAIN error in firefox 84.0.1 using windows 10.  Of course I can hit "advanced" and "accept risk and continue" and load the page, but should I really have to do that?

Forgive me if I have bad form or this is some other dumb issue I created for myself, but I am eager to learn. For what its worth I did search "contribute" in the metafam repo and didnt find any docs (I can submit one if desired), but please let me know if there is more information needed or something specific I should learn about.

If I understand correctly, firefox doesnt like that DNS info is not one of the accepted github alternatives?

![SSL_error](https://user-images.githubusercontent.com/32695229/103473387-e2615f80-4d65-11eb-863c-fa0570cc973c.PNG)

**Comment by SLRead** [comment]
I believe @hammadj has fixed this?  This one can probably close.

**Comment by plasmacorral** [comment]
Yes, issue is resolved and will close.
