### ISSUE TITLE
Update discord thread weights for new threads

### ISSUE THREAD

**Issue by IxaBrjnko** [MetaFam/XP#35]
We should have a similar weight to all of the threads in the Chill Zone except the Tavern, including these two new threads:

#companion-pets - 790340026235748393
and
#item-exchange - 790668773854019594
and possibly moving memery to a lesser weight
#memery - 699325225006792725

There are probably more than a few new threads since this was updated, and it might be also useful to add comments to distinguish the rankings with human readable text, as well as explicitly loading weight behavior for all forums, and/or a review of weights of any channels added since the last update to the weights.

**Comment by SLRead** [comment]
If there is time, this could be bundled in the other decided change to balance XP by increasing Github PRs?  @hammadj 

If not, I'm happy to do this one if you'd like?  I've been playing with my own sourcecred instance for WOCA and have learned lots!
