### ISSUE TITLE
Make it possible to autonomously check and update eth-address

### ISSUE THREAD

**Issue by davort** [MetaFam/XP#41]
Currently this is done in Discord's #set-eth-address channel. 
However, it seems that one can only associate one (wallet) address there. This is the first address one had set in the channel. Any subsequent attempts to update / set a new address _seem_ to be denied, according to the response from the bot 👇 
![image](https://user-images.githubusercontent.com/1573304/107951205-421f6d00-6f98-11eb-90ef-545c87f1d64c.png)

**Comment by luxumbra** [comment]
I believe this is now fixed with the `force` flag. Closing unless we want an additional command for checking our addresses? In which case, re-open and we can get it added.
