### ISSUE TITLE
T-shirt time

### ISSUE THREAD

**Issue by CatalinG90** [MetaFam/XP#53]
![M (5)](https://user-images.githubusercontent.com/77746854/114607786-9c416380-9ca5-11eb-931c-23b82c07e489.png)
![M (4)](https://user-images.githubusercontent.com/77746854/114607791-9e0b2700-9ca5-11eb-876d-994106aa19e2.png)

**Comment by dysbulic** [comment]
This repository is for the SourceCred configuration. There's [another repo and issue](https://github.com/MetaFam/fix-the-world/issues/3) for the t-shirt contest.
